# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: medhy-dohou
type: Opaque
data:
  POSTGRES_PASSWORD: c2VjdXJlcG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  # Example:
  # password: {{ .Values.password | b64enc }}
# stringData:
#   username: admin      # required field for kubernetes.io/basic-auth
#   password: t0p-Secret # required field for kubernetes.io/basic-auth
# immutable: true
---
