# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: medhy-dohou
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: database-pvc
      containers:
      - name: database
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database-data
        image: registry.takima.io/school/proxy/postgres:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 256Mi
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db_path

        ports:
        - containerPort: 5432
          name: database-port
---
