{{- if .Values.front.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-front-service
spec:
  selector:
    app: {{.Values.name }}-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.name }}-front-port
{{- end }}