# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-database-secret
  namespace: medhy-dohou
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
  POSTGRES_USER: {{ .Values.db.username | b64enc }}
---
