# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-database-service
  namespace: medhy-dohou
spec:
  selector:
    app: {{ .Values.name }}-database
  type: ClusterIP
  ports:
  - name: {{ .Values.name }}-db-port
    protocol: TCP
    port: 5432
    targetPort: {{ .Values.name }}-db-port
---
