apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bonus-app
  namespace: medhy-dohou
  labels:
    k8s-app: bonus-app
spec:
  selector:
    matchLabels:
      name: bonus-app
  template:
    metadata:
      labels:
        name: bonus-app
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: bonus-app
        image: registry.takima.io/school/proxy/nginx:1.7.9
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
