apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: medhy-dohou-elastic
spec:
  version: 8.16.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
